name: "DMM CI"

on: 
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - closed
      - synchronize

env:
  SERVICE: dmm-interface

jobs:
  docker:
    runs-on: ubuntu-18.04
    outputs:
      repo_name: ${{ github.event.repository.name }}
      pr_number: ${{ steps.pr_number.outputs.value }}
      image_name: "vietanhs0817/${{ env.SERVICE }}"
      image_tag: ${{ steps.get_tag.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Get PR Number
        id: pr_number
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "PR: $PR_NUMBER"     
          echo "::set-output name=value::$PR_NUMBER"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ env.SERVICE }}-buildx

      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependences
        uses: bahmutov/npm-install@HEAD

      - name: Build
        env:
          CI: false 
        run: yarn build
        
      - name: Get tag
        id: get_tag
        run: |
          short_sha="$(git rev-parse --short HEAD)"
          echo "::set-output name=value::develop-$short_sha"

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          labels: |
            commit=${{ github.sha }}
          tags: |
            ${{ secrets.DOCKER_USERNAME}}/${{ env.SERVICE }}:${{ steps.get_tag.outputs.value}}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  trigger:
    needs:
      - docker
    if: github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'closed'
    runs-on: ubuntu-18.04
    steps:
    - name: Map event
      id: map_event
      run: |
        EVENT="${{ github.event.action }}"
        if [[ "$EVENT" = "reopened" ]]; then
          EVENT=opened 
        fi
        
        echo "::set-output name=value::$EVENT"

    - name: Trigger to Auto deploy PR
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GH_PAT }}
        repository: kybernetwork/infra-config
        event-type: ${{ steps.map_event.outputs.value }}
        client-payload: '{"repo_name": "${{ needs.docker.outputs.repo_name }}", "pr_number": "${{ needs.docker.outputs.pr_number }}", "image_name": "vietanhs0817/${{ env.SERVICE }}", "image_tag": "${{ needs.docker.outputs.image_tag }}"}'
