name: "DMM CI close PR"

on: 
  pull_request:
    types:
      - closed

env:
  SERVICE: dmm-interface

jobs:
  trigger:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get PR Number
      id: pr_number
      run: |
        PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
        echo "PR: $PR_NUMBER"     
        echo "::set-output name=value::$PR_NUMBER"

    - name: Trigger to Auto deploy PR
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GH_PAT }}
        repository: kybernetwork/infra-config
        event-type: ${{ steps.map_event.outputs.value }}
        client-payload: '{"repo_name": "${{ needs.docker.outputs.repo_name }}", "pr_number": "${{ needs.docker.outputs.pr_number }}", "image_name": "vietanhs0817/${{ env.SERVICE }}", "image_tag": "${{ needs.docker.outputs.image_tag }}"}'
